package model

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// User represents a row from 'Attractech.user'.
type User struct {
	ID         uint64    `json:"id"`         // id
	UpdatedAt  time.Time `json:"updated_at"` // updated_at
	CreatedAt  time.Time `json:"created_at"` // created_at
	PublicID   string    `json:"public_id"`  // public_id
	Name       string    `json:"name"`       // name
	Prefrences string    `json:"prefrences"` // prefrences
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the User exists in the database.
func (u *User) Exists() bool {
	return u._exists
}

// Deleted returns true when the User has been marked for deletion from
// the database.
func (u *User) Deleted() bool {
	return u._deleted
}

// Insert inserts the User to the database.
func (u *User) Insert(ctx context.Context, db DB) error {
	switch {
	case u._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case u._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO Attractech.user (` +
		`updated_at, created_at, public_id, name, prefrences` +
		`) VALUES (` +
		`?, ?, ?, ?, ?` +
		`)`
	// run
	logf(sqlstr, u.UpdatedAt, u.CreatedAt, u.PublicID, u.Name, u.Prefrences)
	res, err := db.ExecContext(ctx, sqlstr, u.UpdatedAt, u.CreatedAt, u.PublicID, u.Name, u.Prefrences)
	if err != nil {
		return logerror(err)
	}
	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return logerror(err)
	} // set primary key
	u.ID = uint64(id)
	// set exists
	u._exists = true
	return nil
}

// Update updates a User in the database.
func (u *User) Update(ctx context.Context, db DB) error {
	switch {
	case !u._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case u._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE Attractech.user SET ` +
		`updated_at = ?, created_at = ?, public_id = ?, name = ?, prefrences = ? ` +
		`WHERE id = ?`
	// run
	logf(sqlstr, u.UpdatedAt, u.CreatedAt, u.PublicID, u.Name, u.Prefrences, u.ID)
	if _, err := db.ExecContext(ctx, sqlstr, u.UpdatedAt, u.CreatedAt, u.PublicID, u.Name, u.Prefrences, u.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the User to the database.
func (u *User) Save(ctx context.Context, db DB) error {
	if u.Exists() {
		return u.Update(ctx, db)
	}
	return u.Insert(ctx, db)
}

// Upsert performs an upsert for User.
func (u *User) Upsert(ctx context.Context, db DB) error {
	switch {
	case u._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO Attractech.user (` +
		`id, updated_at, created_at, public_id, name, prefrences` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?` +
		`)` +
		` ON DUPLICATE KEY UPDATE ` +
		`updated_at = VALUES(updated_at), created_at = VALUES(created_at), public_id = VALUES(public_id), name = VALUES(name), prefrences = VALUES(prefrences)`
	// run
	logf(sqlstr, u.ID, u.UpdatedAt, u.CreatedAt, u.PublicID, u.Name, u.Prefrences)
	if _, err := db.ExecContext(ctx, sqlstr, u.ID, u.UpdatedAt, u.CreatedAt, u.PublicID, u.Name, u.Prefrences); err != nil {
		return logerror(err)
	}
	// set exists
	u._exists = true
	return nil
}

// Delete deletes the User from the database.
func (u *User) Delete(ctx context.Context, db DB) error {
	switch {
	case !u._exists: // doesn't exist
		return nil
	case u._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM Attractech.user ` +
		`WHERE id = ?`
	// run
	logf(sqlstr, u.ID)
	if _, err := db.ExecContext(ctx, sqlstr, u.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	u._deleted = true
	return nil
}

// UserByPublicID retrieves a row from 'Attractech.user' as a User.
//
// Generated from index 'public_id'.
func UserByPublicID(ctx context.Context, db DB, publicID string) (*User, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, updated_at, created_at, public_id, name, prefrences ` +
		`FROM Attractech.user ` +
		`WHERE public_id = ?`
	// run
	logf(sqlstr, publicID)
	u := User{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, publicID).Scan(&u.ID, &u.UpdatedAt, &u.CreatedAt, &u.PublicID, &u.Name, &u.Prefrences); err != nil {
		return nil, logerror(err)
	}
	return &u, nil
}

// UserByID retrieves a row from 'Attractech.user' as a User.
//
// Generated from index 'user_id_pkey'.
func UserByID(ctx context.Context, db DB, id uint64) (*User, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, updated_at, created_at, public_id, name, prefrences ` +
		`FROM Attractech.user ` +
		`WHERE id = ?`
	// run
	logf(sqlstr, id)
	u := User{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&u.ID, &u.UpdatedAt, &u.CreatedAt, &u.PublicID, &u.Name, &u.Prefrences); err != nil {
		return nil, logerror(err)
	}
	return &u, nil
}
